os:
#    - linux # Exclude for development to safe Travis minutes
    - osx

matrix:
    include:
        - name: "macOS 13"
          os: osx
          osx_image: xcode10.1

before_script:
- (cd /usr/local/bin/; ln -s ../Cellar/binutils/2.31.1_2/bin/greadelf greadelf)
- (cd /usr/local/bin/; ln -s ../Cellar/binutils/2.31.1_2/bin/gobjcopy gobjcopy)

dist: xenial
language: c
sudo: false

addons:
  apt:
    packages:
    - make
    - unrar
    - autoconf
    - automake
    - libtool
    - libtool-bin
    - gcc
    - g++
    - gperf
    - flex
    - bison
    - texinfo
    - gawk
    - libncurses5-dev
    - libexpat1-dev
    - python
    - python-serial
    - sed
    - git
    - help2man
  homebrew:
    brewfile: true
    update: true

script:
  # Travis sets this due to "language: c", but it confuses autotools configure when cross-building
  - unset CC
  - make
