matrix:
  include:
  - name: "macOS 10.13"
    os: osx
    osx_image: xcode10.1
  - name: "Linux"
    os: linux
    dist: xenial

before_script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (cd /usr/local/bin/; ln -s ../Cellar/binutils/2.31.1_2/bin/greadelf greadelf); fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (cd /usr/local/bin/; ln -s ../Cellar/binutils/2.31.1_2/bin/gobjcopy gobjcopy); fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then hdiutil create -size 3g -volname "esp8266-ws" -fs "Case-sensitive HFS+" ~/esp8266_ws.dmg; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir ~/esp8266-ws; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then hdiutil attach -mountpoint ~/esp8266-ws ~/esp8266_ws.dmg; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp -r /Users/travis/build/strongly-typed/esp-open-sdk ~/esp8266-ws; fi

dist: xenial
language: c
sudo: false

addons:
  apt:
    packages:
    - make
    - unrar
    - autoconf
    - automake
    - libtool
    - libtool-bin
    - gcc
    - g++
    - gperf
    - flex
    - bison
    - texinfo
    - gawk
    - libncurses5-dev
    - libexpat1-dev
    - python
    - python-serial
    - sed
    - git
    - help2man
  homebrew:
    brewfile: true
    update: true

script:
  # Travis sets this due to "language: c", but it confuses autotools configure when cross-building
  - unset CC
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then (cd ~/esp8266-ws/esp-open-sdk; make -j3); fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -j3; fi
